#!/bin/bash
# cretentials.sh

AWS_ACCESS_KEY_ID=""
AWS_SECRET_KEY=""
SSH_PUBLIC_KEY=""
ACCOUNT_URL=""

export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_KEY=$AWS_SECRET_KEY
export SSH_PUBLIC_KEY=$SSH_PUBLIC_KEY
export ACCOUNT_URL=$ACCOUNT_URL